/* type entries, generated by maketypes.awk */

  { "EelBackgroundImagePlacement", &EEL_TYPE_BACKGROUND_IMAGE_PLACEMENT,
    G_TYPE_ENUM, _eel_background_image_placement_values },
  { "EelGdkGeometryFlags", &EEL_TYPE_GDK_GEOMETRY_FLAGS,
    G_TYPE_ENUM, _eel_gdk_geometry_flags_values },
  { "EelEllipsizeMode", &EEL_TYPE_ELLIPSIZE_MODE,
    G_TYPE_ENUM, _eel_ellipsize_mode_values },
  { "EelJustification", &EEL_TYPE_JUSTIFICATION,
    G_TYPE_ENUM, _eel_justification_values },
